[package]
name = "playdir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matroska = "0.26.1"
plist = "1.6.0"
serde = "1.0.195"
serde_json = "1.0.111"
